# Generated by Django 3.1.6 on 2021-07-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.SlugField(max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('text', models.TextField(default='', verbose_name='Text')),
                ('date', models.DateField(auto_now=True, verbose_name='Date')),
                ('exp_date', models.DateField(auto_now=True, verbose_name='Exp_date')),
            ],
        ),
    ]
